### ISSUE TITLE
How to config etc dir?

### ISSUE THREAD

**Issue by jomonkj** [hiqdev/hidev-nginx#1]

**Comment by hiqsol** [comment]
What is the path you to set?

**Comment by hiqsol** [comment]
Have you seen 
https://github.com/hiqdev/hidev-nginx/blob/master/src/components/Nginx.php#L178

**Comment by jomonkj** [comment]
sorry, my mistake,
that's configurable
https://github.com/hiqdev/hidev-nginx/blob/fe7a12ca427ecf3916255bd7ea41b34d3688da5b/src/components/Nginx.php#L165
